import type { Metadata } from "next";
import Link from "next/link";
import { MoveRight } from "lucide-react";

export const metadata: Metadata = {
	title: "Authentication | Loom Clone",
	description: "Generated by create next app",
};

export default function AuthLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className='w-full min-h-screen flex items-start justify-between'>
			<nav className='w-1/4 h-screen md:block hidden'>
				<div className='w-1/4 bg-blue-500 h-screen md:block hidden fixed top-0 z-10 p-8'>
					<section className='absolute bottom-20 px-2 flex flex-col'>
						<Link href='/' className='font-bold text-2xl text-gray-50'>
							Loom Clone
						</Link>
						<p className='opacity-70 mt-2 text-sm'>
							Seamless video upload and sharing{" "}
							<MoveRight className='inline-block ml-1' />
						</p>
					</section>
				</div>
			</nav>

			{children}
		</main>
	);
}